const resdata = {
  cards: [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "342560",
        name: "Dhaba 1947",
        uuid: "23cfe142-1396-4102-ace5-9ba8e3141d4e",
        city: "2",
        area: "Sushant Lok",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "fnlivbxy0nsfnicpccyv",
        cuisines: ["North Indian", "Tandoor", "Mughlai"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 7,
        slugs: {
          restaurant: "dhaba-1947-dlf-phase-4-dlf-phase-4",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "Block H 239, 240 Sushant Shopping Arcade. Locality & Area: Sushant Lok Phase - 1",
        locality: "Sushant Shopping Arcade",
        parentId: 14248,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8700,
          message: "",
          title: "Delivery Charge",
          amount: "8700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7361602~p=1~eid=00000189-2c4a-9442-0189-36ee00120106~srvts=1688665232450",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "342560",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 7,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "280771",
        name: "Chamail Singh Da Dhaba",
        uuid: "5252be69-c407-4777-a241-d1e3fbdb7105",
        city: "2",
        area: "Sector 39",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "ge2lzhxpx7izcbpseria",
        cuisines: ["North Indian"],
        tags: [],
        costForTwo: 29900,
        costForTwoString: "₹299 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "chamail-singh-da-dhaba-sohna-road-sohna-road-2",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "1063,\tShop\tNo\t4,\tSector 39,\tVill\tJharsa,\tGurgaon,\tGurgaon\t(Haryana),\t-\t122001",
        locality: "Jharsa",
        parentId: 57541,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5700,
          message: "",
          title: "Delivery Charge",
          amount: "5700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "280771",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "2.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "651214",
        name: "McDonald's",
        uuid: "f78bb688-db2e-47a7-94dd-8db3a55f1a48",
        city: "2",
        area: "Sector 77",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "08eee882fda81b68e5c36e3a5d89d8c0",
        cuisines: ["American", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "mcdonalds-sector-14-sector-14",
          city: "gurgaon",
        },
        cityState: "2",
        address: "Unit No. SCF -77, Sector 14 Market, HUDA, Gurgaon",
        locality: "Huda Market",
        parentId: 630,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "651214",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "551617",
        name: "That Andhra Guy",
        uuid: "662683a5-f233-40a8-99fe-7e69ee142061",
        city: "2",
        area: "Sector 41",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "6c9a52d5065a550ae5c08cb432f6ec53",
        cuisines: ["North Indian", "South Indian", "Biryani", "Tandoor"],
        tags: [],
        costForTwo: 39900,
        costForTwoString: "₹399 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "that-andhra-guy-huda-city-huda-city-2",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "Building No.-105, Near Star PG, Sector 41, Gurugram, Haryana- 122002",
        locality: "South City I",
        parentId: 285169,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 5700,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5700,
          message: "",
          title: "Delivery Charge",
          amount: "5700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7306956~p=4~eid=00000189-2c4a-9442-0189-36ef00120475~srvts=1688665232450",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "551617",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "154653",
        name: "Jagdish Vaishno Dhaba",
        uuid: "a783085e-830a-4a33-8831-1274bd944def",
        city: "2",
        area: "Old Railway Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "seyuhw8itjtlmvm7wscy",
        cuisines: ["Indian", "North Indian", "Biryani", "Tandoor", "Punjabi"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 13,
        minDeliveryTime: 13,
        maxDeliveryTime: 13,
        slaString: "13 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "jagdish-vaishno-dhaba-old-gurgaon-zone-6",
          city: "gurgaon",
        },
        cityState: "2",
        address: "JAGDISH VAISHNO DHABA OPP Gurgaon Dreams Mall ",
        locality: "Sector 4",
        parentId: 15300,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "154653",
          deliveryTime: 13,
          minDeliveryTime: 13,
          maxDeliveryTime: 13,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "11672",
        name: "Pizza Hut",
        uuid: "4f4dde4a-a977-4ac1-a3a0-bf036dcf9632",
        city: "2",
        area: "Sector 4",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "pizza-hut-delivery-old-gurgaon-zone-6",
          city: "gurgaon",
        },
        cityState: "2",
        address: "SCF No # 37, HUDA Market,Sector-4 Gurgaon,Haryana",
        locality: "Huda Market",
        parentId: 721,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "FREE ITEM",
          subHeader: "",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "11672",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "20424",
        name: "Subway",
        uuid: "94e4ee91-b6f6-4ef3-ad56-e870d0b3b91e",
        city: "2",
        area: "Sector 50",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
        cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant: "subway-sohna-road-gurgaon-sohna-road",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "SUBWAY  B-003, BUSINESS ZONE, NIRVANA COUNTRY, SECTOR 50, GURGAON",
        locality: "Nirvana Country",
        parentId: 2,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8700,
          message: "",
          title: "Delivery Charge",
          amount: "8700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7201281~p=7~eid=00000189-2c4a-9442-0189-36f000120700~srvts=1688665232450",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "20424",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "197649",
        name: " Punjabi Dhaba",
        uuid: "03b1b762-3a7b-474e-8bc7-585416dfd1c9",
        city: "2",
        area: "Sector 14",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "ulptri22qje8lmaeqjsy",
        cuisines: ["Beverages", "Chinese", "Indian", "Italian", "Continental"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: "alien-food-dlf-phase-4-dlf-phase-4",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "2268/3,OLD DELHI GURUGRAM ROAD OPPOSITE ICICI BANK SECTOR-14 GURUGRAM HARYANA, Gurgaon, Gurugram, Haryana-122001",
        locality: "Ragev Nagar",
        parentId: 1476,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "197649",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "48174",
        name: "Shama Chicken Corner",
        uuid: "caeb4c79-b41c-44c6-847e-b92f2dfa4c57",
        city: "2",
        area: "Sohna Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "hle5hahxhcsadiboo5c5",
        cuisines: ["Biryani", "Mughlai"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 6.199999809265137,
        slugs: {
          restaurant: "shama-chicken-fazilpur-chowk-sohna-road",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "Shop No.2, Fazilpur Chowk, Near Omaxe City Center, Sohna Road",
        locality: "Fazilpur Chowk",
        parentId: 13769,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7700,
          message: "",
          title: "Delivery Charge",
          amount: "7700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "48174",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 6.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "626128",
        name: "Naan Chowk",
        uuid: "7353b50f-6b71-4708-85fd-cf5efdb43182",
        city: "2",
        area: "Sector 39",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "up1efjiwudplch17bud6",
        cuisines: ["Indian", "Chinese", "North Indian", "Snacks"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "naan-chowk-sohna-road-sohna-road",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "PROP.NO-510, ROOM NO-2, 1st FLOOR,NEAR LAL KUAA, JHARSA VILLAGE, GURGAON-122003 HARYANA",
        locality: "Jharsa",
        parentId: 372381,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4900,
          message: "",
          title: "Delivery Charge",
          amount: "4900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7259584~p=10~eid=00000189-2c4a-9442-0189-36f100120a1a~srvts=1688665232450",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "626128",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "125878",
        name: "Burger King",
        uuid: "36c9ddaf-4e28-421e-98fa-534b984a61f9",
        city: "2",
        area: "Sector 4",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "burger-king-dreamz-mall-old-gurgaon-zone-6",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "UGF-2 & FF-1, GURGAON DREAMZ, SECTOR-4,7 CROSSING OLD RAILWAY ROAD, GURGAON-122001",
        locality: "Old Railway Road",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "EVERY ITEM",
          subHeader: "@ ₹129",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "125878",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "457380",
        name: "Danny's Fried Chicken",
        uuid: "f80ba74a-82f2-4b16-b40c-9f016cb23be6",
        city: "2",
        area: "South City 2",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "c2nsaevy27a8jx84vnk6",
        cuisines: ["Fast Food", "Snacks", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 6,
        slugs: {
          restaurant: "danny's-fried-chicken-sohna-road-sohna-road",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "D 101, First Floor unitech arcadia - II (Rodeo Drive) South City 2, Sector 49 Gurugram, haryana, 122002",
        locality: "South City 2",
        parentId: 274349,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7700,
          message: "",
          title: "Delivery Charge",
          amount: "7700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7375786~p=16~eid=00000189-2c4a-9442-0189-36f30012107d~srvts=1688665232450",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "457380",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 6,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "557228",
        name: "Chef Mantra",
        uuid: "849fab30-f32e-492e-a7ef-80daba41b82a",
        city: "2",
        area: "Sector 45",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "h7wbfbhtwsagfa4ecklk",
        cuisines: ["North Indian", "Chinese", "Snacks"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 4.5,
        slugs: {
          restaurant: "chef-mantra-old-gurgaon-(zone-6)-old-gurgaon-(zone-6)",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "Jal Vihar, Jal Vihar Colony, Sector 46, Gurugram, Haryana 122003",
        locality: "Jal Vihar Colony",
        parentId: 334962,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5700,
          message: "",
          title: "Delivery Charge",
          amount: "5700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "557228",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 4.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "638349",
        name: "Yum Hum Bakers",
        uuid: "97706a65-362a-440e-a2c7-88bb6c46afaa",
        city: "2",
        area: "Sector 17",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "ubljjem7umgi2tb7t4mu",
        cuisines: ["Ice Cream Cakes", "Desserts", "Bakery"],
        tags: [],
        costForTwo: 19900,
        costForTwoString: "₹199 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 4.099999904632568,
        slugs: {
          restaurant: "yum-hum-bakers-sector-14-sector-14",
          city: "gurgaon",
        },
        cityState: "2",
        address:
          "Mehrauli Gurugram road shukrali sector 17 Abhay Singh market, Shop no 1, nearby MDI college, Sukhrali, Sector 17, Gurugram, Haryana 122001, India",
        locality: "Abhay Singh Market",
        parentId: 385248,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 5700,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5700,
          message: "",
          title: "Delivery Charge",
          amount: "5700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "638349",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 4.099999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "27213",
        name: "Prince Ki Rasoi",
        uuid: "e3452a50-cc17-4a82-ba5a-508441f5e2e6",
        city: "2",
        area: "Sector 45",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "dfbjrjlhn6f5boxv1hbv",
        cuisines: ["North Indian", "Chinese", "Mughlai"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 5.900000095367432,
        slugs: {
          restaurant: "prince-ki-rasoi-sector-45-huda-city",
          city: "gurgaon",
        },
        cityState: "2",
        address: "410, Opposite Ramada Hotel, Sector 45, Gurgaon",
        locality: "Ramada Hotel",
        parentId: 13952,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6700,
          message: "",
          title: "Delivery Charge",
          amount: "6700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "27213",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 5.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
  ],
};

export default resdata;
